/**
 * This script generates the exports functionality for the node API.
 *
 * it exports chef as default, but all the wrapped operations as
 * other top level exports.
 *
 * @author d98762656 [d98762625@gmail.com]
 * @copyright Crown Copyright 2018
 * @license Apache-2.0
 */

/* eslint no-console: 0 */

import fs from "fs";
import path from "path";
import * as operations from "../../../core/operations/index.mjs";
import { decapitalise } from "../../apiUtils.mjs";
import excludedOperations from "../excludedOperations.mjs";

// 汉化后操作名为中文，Node API 需兼容官方英文键与英文报错显示名
const EXCLUDED_EN = {
    "分支": ["fork", "Fork"],
    "合并": ["merge", "Merge"],
    "跳转": ["jump", "Jump"],
    "条件跳转": ["conditionalJump", "Conditional Jump"],
    "标签": ["label", "Label"],
    "注释": ["comment", "Comment"],
    "JavaScript 美化": ["javaScriptBeautify", "JavaScriptBeautify"],
    "JavaScript 压缩": ["javaScriptMinify", "JavaScriptMinify"],
    "JavaScript 解析器": ["javaScriptParser", "JavaScriptParser"],
    "语法高亮": ["syntaxHighlighter", "SyntaxHighlighter"],
};

const includedOperations = Object.keys(operations).filter((op => excludedOperations.indexOf(op) === -1));

const dir = path.join(`${process.cwd()}/src/node`);
if (!fs.existsSync(dir)) {
    console.log("\nCWD: " + process.cwd());
    console.log("Error: generateNodeIndex.mjs should be run from the project root");
    console.log("Example> node --experimental-modules src/node/config/scripts/generateNodeIndex.mjs");
    process.exit(1);
}

let code = `/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/node/config/scripts/generateNodeIndex.mjs
*
* @author d98762625 [d98762625@gmail.com]
* @copyright Crown Copyright 2019
* @license Apache-2.0
*/

/* eslint camelcase: 0 */


import NodeDish from "./NodeDish.mjs";
import { _wrap, help, bake, _explainExcludedFunction } from "./api.mjs";
import File from "./File.mjs";
import { OperationError, DishError, ExcludedOperationError } from "../core/errors/index.mjs";
import {
    // import as core_ to avoid name clashes after wrap.
`;

includedOperations.forEach((op) => {
    // prepend with core_ to avoid name collision later.
    code += `    ${op} as core_${op},\n`;
});

code +=`
} from "../core/operations/index.mjs";

global.File = File;

/**
 * generateChef
 *
 * Creates decapitalised, wrapped ops in chef object for default export.
 */
function generateChef() {
    return {
`;

includedOperations.forEach((op) => {
    code += `        "${decapitalise(op)}": _wrap(core_${op}),\n`;
});

excludedOperations.forEach((op) => {
    const [enKey, enDisplay] = EXCLUDED_EN[op] || [decapitalise(op), op];
    code += `        "${enKey}": _explainExcludedFunction("${op}", "${enDisplay}"),\n`;
});

code += `    };
}

const chef = generateChef();
// Add some additional features to chef object.
chef.help = help;
chef.Dish = NodeDish;

// Define consts here so we can add to top-level export - wont allow
// export of chef property.
`;

Object.keys(operations).forEach((op) => {
    code += `const ${decapitalise(op)} = chef.${decapitalise(op)};\n`;
});

code +=`

// Define array of all operations to create register for bake.
const operations = [\n`;

Object.keys(operations).forEach((op) => {
    code += `    ${decapitalise(op)},\n`;
});

code += `];

chef.bake = bake;
export default chef;

// Operations as top level exports.
export {
    operations,
`;

Object.keys(operations).forEach((op) => {
    code += `    ${decapitalise(op)},\n`;
});

code += "    NodeDish as Dish,\n";
code += "    bake,\n";
code += "    help,\n";
code += "    OperationError,\n";
code += "    ExcludedOperationError,\n";
code += "    DishError,\n";
code += "};\n";


fs.writeFileSync(
    path.join(dir, "./index.mjs"),
    code
);
