/**
 * @author n1073645 [n1073645@gmail.com]
 * @copyright Crown Copyright 2022
 * @license Apache-2.0
 */
import TestRegister from "../../lib/TestRegister.mjs";
import {ELF32_LE, ELF32_BE, ELF64_LE, ELF64_BE} from "../../samples/Executables.mjs";

// eslint-disable-next-line no-unused-vars
const ELF32_LE_OUTPUT = "============================== ELF Header ==============================\nMagic:                        \x7fELF\nFormat:                       32-bit\nEndianness:                   Little\nVersion:                      1\nABI:                          System V\nABI Version:                  0\nType:                         Executable File\nInstruction Set Architecture: x86\nELF Version:                  1\nEntry Point:                  0x8062150\nEntry PHOFF:                  0x34\nEntry SHOFF:                  0x54\nFlags:                        00000000\nELF Header Size:              52 bytes\nProgram Header Size:          32 bytes\nProgram Header Entries:       1\nSection Header Size:          40 bytes\nSection Header Entries:       3\nSection Header Names:         0\n\n============================== Program Header ==============================\nProgram Header Type:          Program Header Table\nOffset Of Segment:            52\nVirtual Address of Segment:   134512692\nPhysical Address of Segment:  134512692\nSize of Segment:              256 bytes\nSize of Segment in Memory:    256 bytes\nFlags:                        Execute,Read\n\n============================== Section Header ==============================\nType:                         String Table\nSection Name:                 .shstrab\nFlags:                        \nSection Vaddr in memory:      0\nOffset of the section:        204\nSection Size:                 28\nAssociated Section:           0\nSection Extra Information:    0\n\nType:                         Symbol Table\nSection Name:                 .symtab\nFlags:                        \nSection Vaddr in memory:      0\nOffset of the section:        230\nSection Size:                 16\nAssociated Section:           0\nSection Extra Information:    0\n\nType:                         String Table\nSection Name:                 .strtab\nFlags:                        \nSection Vaddr in memory:      0\nOffset of the section:        245\nSection Size:                 4\nAssociated Section:           0\nSection Extra Information:    0\n\n============================== Symbol Table ==============================\nSymbol Name:                  test";
// eslint-disable-next-line no-unused-vars
const ELF32_BE_OUTPUT = "============================== ELF Header ==============================\nMagic:                        \x7fELF\nFormat:                       32-bit\nEndianness:                   Big\nVersion:                      1\nABI:                          System V\nABI Version:                  0\nType:                         Executable File\nInstruction Set Architecture: x86\nELF Version:                  1\nEntry Point:                  0x8062150\nEntry PHOFF:                  0x34\nEntry SHOFF:                  0x54\nFlags:                        00000000\nELF Header Size:              52 bytes\nProgram Header Size:          32 bytes\nProgram Header Entries:       1\nSection Header Size:          40 bytes\nSection Header Entries:       3\nSection Header Names:         0\n\n============================== Program Header ==============================\nProgram Header Type:          Program Header Table\nOffset Of Segment:            52\nVirtual Address of Segment:   134512692\nPhysical Address of Segment:  134512692\nSize of Segment:              256 bytes\nSize of Segment in Memory:    256 bytes\nFlags:                        Execute,Read\n\n============================== Section Header ==============================\nType:                         String Table\nSection Name:                 .shstrab\nFlags:                        \nSection Vaddr in memory:      0\nOffset of the section:        204\nSection Size:                 28\nAssociated Section:           0\nSection Extra Information:    0\n\nType:                         Symbol Table\nSection Name:                 .symtab\nFlags:                        \nSection Vaddr in memory:      0\nOffset of the section:        230\nSection Size:                 16\nAssociated Section:           0\nSection Extra Information:    0\n\nType:                         String Table\nSection Name:                 .strtab\nFlags:                        \nSection Vaddr in memory:      0\nOffset of the section:        245\nSection Size:                 4\nAssociated Section:           0\nSection Extra Information:    0\n\n============================== Symbol Table ==============================\nSymbol Name:                  test";
// eslint-disable-next-line no-unused-vars
const ELF64_LE_OUTPUT = "============================== ELF Header ==============================\nMagic:                        \x7fELF\nFormat:                       64-bit\nEndianness:                   Little\nVersion:                      1\nABI:                          System V\nABI Version:                  0\nType:                         Executable File\nInstruction Set Architecture: AMD x86-64\nELF Version:                  1\nEntry Point:                  0x8062150\nEntry PHOFF:                  0x40\nEntry SHOFF:                  0x78\nFlags:                        00000000\nELF Header Size:              64 bytes\nProgram Header Size:          56 bytes\nProgram Header Entries:       1\nSection Header Size:          64 bytes\nSection Header Entries:       3\nSection Header Names:         0\n\n============================== Program Header ==============================\nProgram Header Type:          Program Header Table\nFlags:                        Execute,Read\nOffset Of Segment:            52\nVirtual Address of Segment:   134512692\nPhysical Address of Segment:  134512692\nSize of Segment:              256 bytes\nSize of Segment in Memory:    256 bytes\n\n============================== Section Header ==============================\nType:                         String Table\nSection Name:                 .shstrab\nFlags:                        \nSection Vaddr in memory:      0\nOffset of the section:        312\nSection Size:                 28\nAssociated Section:           0\nSection Extra Information:    0\n\nType:                         Symbol Table\nSection Name:                 .symtab\nFlags:                        \nSection Vaddr in memory:      0\nOffset of the section:        336\nSection Size:                 16\nAssociated Section:           0\nSection Extra Information:    0\n\nType:                         String Table\nSection Name:                 .strtab\nFlags:                        \nSection Vaddr in memory:      0\nOffset of the section:        361\nSection Size:                 4\nAssociated Section:           0\nSection Extra Information:    0\n\n============================== Symbol Table ==============================\nSymbol Name:                  test";
// eslint-disable-next-line no-unused-vars
const ELF64_BE_OUTPUT = "============================== ELF Header ==============================\nMagic:                        \x7fELF\nFormat:                       64-bit\nEndianness:                   Big\nVersion:                      1\nABI:                          System V\nABI Version:                  0\nType:                         Executable File\nInstruction Set Architecture: AMD x86-64\nELF Version:                  1\nEntry Point:                  0x8062150\nEntry PHOFF:                  0x40\nEntry SHOFF:                  0x78\nFlags:                        00000000\nELF Header Size:              64 bytes\nProgram Header Size:          56 bytes\nProgram Header Entries:       1\nSection Header Size:          64 bytes\nSection Header Entries:       3\nSection Header Names:         0\n\n============================== Program Header ==============================\nProgram Header Type:          Program Header Table\nFlags:                        Execute,Read\nOffset Of Segment:            52\nVirtual Address of Segment:   134512692\nPhysical Address of Segment:  134512692\nSize of Segment:              256 bytes\nSize of Segment in Memory:    256 bytes\n\n============================== Section Header ==============================\nType:                         String Table\nSection Name:                 .shstrab\nFlags:                        \nSection Vaddr in memory:      0\nOffset of the section:        312\nSection Size:                 28\nAssociated Section:           0\nSection Extra Information:    0\n\nType:                         Symbol Table\nSection Name:                 .symtab\nFlags:                        \nSection Vaddr in memory:      0\nOffset of the section:        336\nSection Size:                 16\nAssociated Section:           0\nSection Extra Information:    0\n\nType:                         String Table\nSection Name:                 .strtab\nFlags:                        \nSection Vaddr in memory:      0\nOffset of the section:        361\nSection Size:                 4\nAssociated Section:           0\nSection Extra Information:    0\n\n============================== Symbol Table ==============================\nSymbol Name:                  test";

TestRegister.addTests([
    {
        name: "ELF Info invalid ELF.",
        input: "\x7f\x00\x00\x00",
        expectedOutput: "无效的 ELF 文件",
        recipeConfig: [
            {
                op: "ELF Info",
                args: [],
            },
        ],
    },
    {
        name: "ELF Info 32-bit ELF Little Endian.",
        input: ELF32_LE,
        expectedOutput: "============================== ELF 头部 ==============================\n魔数:                           ELF\n格式:                           32 位\n字节序:                          小端\n版本:                           1\nABI:                          System V\nABI 版本:                       0\n类型:                           可执行文件\n指令集架构:                        x86\nELF 版本:                       1\n入口点:                          0x8062150\n程序头偏移(PHOFF):                 0x34\n节头偏移(SHOFF):                  0x54\n标志:                           00000000\nELF 头大小:                      52 字节\n程序头大小:                        32 字节\n程序头项数:                        1\n节头大小:                         40 字节\n节头项数:                         3\n节名字符串表:                       0\n\n============================== 程序头 ==============================\n程序头类型:                        程序头表\n段偏移:                          52\n段虚拟地址:                        134512692\n段物理地址:                        134512692\n段大小:                          256 字节\n内存中段大小:                       256 字节\n标志:                           执行,读取\n\n============================== 节头 ==============================\n类型:                           字符串表\n节名称:                          .shstrab\n标志:                           \n节内存虚拟地址:                      0\n节偏移:                          204\n节大小:                          28\n关联节:                          0\n节附加信息:                        0\n\n类型:                           符号表\n节名称:                          .symtab\n标志:                           \n节内存虚拟地址:                      0\n节偏移:                          230\n节大小:                          16\n关联节:                          0\n节附加信息:                        0\n\n类型:                           字符串表\n节名称:                          .strtab\n标志:                           \n节内存虚拟地址:                      0\n节偏移:                          245\n节大小:                          4\n关联节:                          0\n节附加信息:                        0\n\n============================== 符号表 ==============================\n符号名称:                         test",
        recipeConfig: [
            {
                op: "From Hex",
                args: ["None"],
            },
            {
                op: "ELF Info",
                args: [],
            },
        ],
    },
    {
        name: "ELF Info 32-bit ELF Big Endian.",
        input: ELF32_BE,
        expectedOutput: "============================== ELF 头部 ==============================\n魔数:                           ELF\n格式:                           32 位\n字节序:                          大端\n版本:                           1\nABI:                          System V\nABI 版本:                       0\n类型:                           可执行文件\n指令集架构:                        x86\nELF 版本:                       1\n入口点:                          0x8062150\n程序头偏移(PHOFF):                 0x34\n节头偏移(SHOFF):                  0x54\n标志:                           00000000\nELF 头大小:                      52 字节\n程序头大小:                        32 字节\n程序头项数:                        1\n节头大小:                         40 字节\n节头项数:                         3\n节名字符串表:                       0\n\n============================== 程序头 ==============================\n程序头类型:                        程序头表\n段偏移:                          52\n段虚拟地址:                        134512692\n段物理地址:                        134512692\n段大小:                          256 字节\n内存中段大小:                       256 字节\n标志:                           执行,读取\n\n============================== 节头 ==============================\n类型:                           字符串表\n节名称:                          .shstrab\n标志:                           \n节内存虚拟地址:                      0\n节偏移:                          204\n节大小:                          28\n关联节:                          0\n节附加信息:                        0\n\n类型:                           符号表\n节名称:                          .symtab\n标志:                           \n节内存虚拟地址:                      0\n节偏移:                          230\n节大小:                          16\n关联节:                          0\n节附加信息:                        0\n\n类型:                           字符串表\n节名称:                          .strtab\n标志:                           \n节内存虚拟地址:                      0\n节偏移:                          245\n节大小:                          4\n关联节:                          0\n节附加信息:                        0\n\n============================== 符号表 ==============================\n符号名称:                         test",
        recipeConfig: [
            {
                op: "From Hex",
                args: ["None"],
            },
            {
                op: "ELF Info",
                args: [],
            },
        ],
    },
    {
        name: "ELF Info 64-bit ELF Little Endian.",
        input: ELF64_LE,
        expectedOutput: "============================== ELF 头部 ==============================\n魔数:                           ELF\n格式:                           64 位\n字节序:                          小端\n版本:                           1\nABI:                          System V\nABI 版本:                       0\n类型:                           可执行文件\n指令集架构:                        AMD x86-64\nELF 版本:                       1\n入口点:                          0x8062150\n程序头偏移(PHOFF):                 0x40\n节头偏移(SHOFF):                  0x78\n标志:                           00000000\nELF 头大小:                      64 字节\n程序头大小:                        56 字节\n程序头项数:                        1\n节头大小:                         64 字节\n节头项数:                         3\n节名字符串表:                       0\n\n============================== 程序头 ==============================\n程序头类型:                        程序头表\n标志:                           执行,读取\n段偏移:                          52\n段虚拟地址:                        134512692\n段物理地址:                        134512692\n段大小:                          256 字节\n内存中段大小:                       256 字节\n\n============================== 节头 ==============================\n类型:                           字符串表\n节名称:                          .shstrab\n标志:                           \n节内存虚拟地址:                      0\n节偏移:                          312\n节大小:                          28\n关联节:                          0\n节附加信息:                        0\n\n类型:                           符号表\n节名称:                          .symtab\n标志:                           \n节内存虚拟地址:                      0\n节偏移:                          336\n节大小:                          16\n关联节:                          0\n节附加信息:                        0\n\n类型:                           字符串表\n节名称:                          .strtab\n标志:                           \n节内存虚拟地址:                      0\n节偏移:                          361\n节大小:                          4\n关联节:                          0\n节附加信息:                        0\n\n============================== 符号表 ==============================\n符号名称:                         test",
        recipeConfig: [
            {
                op: "From Hex",
                args: ["None"],
            },
            {
                op: "ELF Info",
                args: [],
            },
        ],
    },
    {
        name: "ELF Info 64-bit ELF Big Endian.",
        input: ELF64_BE,
        expectedOutput: "============================== ELF 头部 ==============================\n魔数:                           ELF\n格式:                           64 位\n字节序:                          大端\n版本:                           1\nABI:                          System V\nABI 版本:                       0\n类型:                           可执行文件\n指令集架构:                        AMD x86-64\nELF 版本:                       1\n入口点:                          0x8062150\n程序头偏移(PHOFF):                 0x40\n节头偏移(SHOFF):                  0x78\n标志:                           00000000\nELF 头大小:                      64 字节\n程序头大小:                        56 字节\n程序头项数:                        1\n节头大小:                         64 字节\n节头项数:                         3\n节名字符串表:                       0\n\n============================== 程序头 ==============================\n程序头类型:                        程序头表\n标志:                           执行,读取\n段偏移:                          52\n段虚拟地址:                        134512692\n段物理地址:                        134512692\n段大小:                          256 字节\n内存中段大小:                       256 字节\n\n============================== 节头 ==============================\n类型:                           字符串表\n节名称:                          .shstrab\n标志:                           \n节内存虚拟地址:                      0\n节偏移:                          312\n节大小:                          28\n关联节:                          0\n节附加信息:                        0\n\n类型:                           符号表\n节名称:                          .symtab\n标志:                           \n节内存虚拟地址:                      0\n节偏移:                          336\n节大小:                          16\n关联节:                          0\n节附加信息:                        0\n\n类型:                           字符串表\n节名称:                          .strtab\n标志:                           \n节内存虚拟地址:                      0\n节偏移:                          361\n节大小:                          4\n关联节:                          0\n节附加信息:                        0\n\n============================== 符号表 ==============================\n符号名称:                         test",
        recipeConfig: [
            {
                op: "From Hex",
                args: ["None"],
            },
            {
                op: "ELF Info",
                args: [],
            },
        ],
    },
]);
